// C02EX17.CPP

#include <iostream>
#include <print>

using namespace std;

int main(void)
{
  int16_t value = 10;

  println("Decimal value .................: {}", value);
  println("Binary value ..................: {:b}", val-ue);
  println("Octal value ...................: {:o}", val-ue);
  println("Hexadecimal value (lowercase) .: {:x}", val-ue);
  println("Hexadecimal value (uppercase) .: {:X}", val-ue);

  println("");
  print("Press <Enter> to exit... ");
  cin.get();
  return 0;
}
